name: Release

on:
  push:
    branches:
      - alpha

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: 🔄 Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🌙 Setup Moonrepo and Prototools
        uses: DynamicQuants/actions/moon@main
      - name: 📦 Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          commit: '🔧 chore: update version'
          title: '🔧 chore: update version'
          version: 'moon ci :version'
          publish: 'moon ci :publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 🔖 Create tag
        uses: rickstaa/action-create-tag@v1
        if: steps.changesets.outcome == 'success' && steps.changesets.outputs.published == 'true'
        with:
          tag: '${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}'
          tag_exists_error: false
          message: 'Release ${tag}'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
