name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: ./.github/actions/moon
        name: 🌙 Setup Moon and build the project
        with:
          moon-version: '1.30.5'
          proto-version: '0.44.2'
          command: 'moon ci :build && ls -la'
